import { TourPackage } from "@/types";

// Re-export from central lib/formatters – single source of truth
export { formatTourPrice } from "@/lib/formatters";

export const tours: TourPackage[] = [
  {
    id: "1",
    title: "Jogja Complete Package",
    description:
      "A complete package to enjoy all the beauty of Yogyakarta. Historic temples, exotic beaches, nature, culture, and culinary delights all in one trip.",
    imageUrl: "/images/tour-labuan.jpg",
    estimatedPrice: 650000,
    priceType: "per_person",
    duration: "1 Day 1 Night",
    minPax: 1,
    maxPax: 10,
    startTime: "07:00",
    endTime: "20:00",
    includes: ["Transportation", "Tour guide", "Entrance tickets"],
    excludes: ["Meals", "Personal expenses"],
    vehicleOptions: [
      { id: "bus-1", name: "Mini Bus", capacity: 10, pricePerDay: 650000 },
    ],
    destinationTags: ["Candi Borobudur", "Candi Prambanan", "Hutan Pinus Mangunan", "Pantai Parangtritis"],
    recommendation: "Recommended",
    status: "active",
  },
  {
    id: "2",
    title: "Jogja Private Trip",
    description:
      "Enjoy a private and flexible trip with your own vehicle and driver. Perfect for families or small groups.",
    imageUrl: "/images/tour-yogyakarta.jpg",
    estimatedPrice: 2000000,
    priceType: "per_car",
    duration: "1 Day",
    minPax: 1,
    maxPax: 6,
    startTime: "08:00",
    endTime: "18:00",
    includes: ["Transportation", "Driver", "Fuel"],
    excludes: ["Meals", "Entrance tickets", "Personal expenses"],
    vehicleOptions: [
      { id: "avanza-1", name: "Avanza", capacity: 6, pricePerDay: 2000000 },
      { id: "xenia-1", name: "Xenia", capacity: 6, pricePerDay: 2000000 },
    ],
    destinationTags: ["Borobudur", "Prambanan"],
    recommendation: "Best Seller",
    status: "active",
  },
  {
    id: "3",
    title: "Private City Tour",
    description:
      "Explore the heart of Yogyakarta with a private city tour experience.",
    imageUrl: "/images/tour-bali.jpg",
    estimatedPrice: 2500000,
    priceType: "per_car",
    duration: "1 Day",
    minPax: 1,
    maxPax: 4,
    startTime: "09:00",
    endTime: "17:00",
    includes: ["Transportation", "Driver", "Fuel"],
    excludes: ["Meals", "Personal expenses"],
    vehicleOptions: [
      { id: "city-car-1", name: "City Car", capacity: 4, pricePerDay: 2500000 },
    ],
    destinationTags: ["Malioboro", "Keraton", "Taman Sari"],
    recommendation: "None",
    status: "active",
  },
  {
    id: "4",
    title: "Private Heritage Tour",
    description:
      "Discover Yogyakarta's rich heritage with a comfortable private trip.",
    imageUrl: "/images/tour-bromo.jpg",
    estimatedPrice: 2700000,
    priceType: "per_car",
    duration: "1 Day",
    minPax: 1,
    maxPax: 4,
    startTime: "07:00",
    endTime: "17:00",
    includes: ["Transportation", "Driver", "Fuel", "Tour guide"],
    excludes: ["Meals", "Personal expenses"],
    vehicleOptions: [
      { id: "city-car-2", name: "City Car", capacity: 4, pricePerDay: 2700000 },
    ],
    destinationTags: ["Borobudur", "Prambanan"],
    recommendation: "None",
    status: "active",
  },
  {
    id: "5",
    title: "Sunrise Merapi Tour",
    description:
      "Experience the stunning sunrise at Mount Merapi with an adventurous jeep tour.",
    imageUrl: "/images/tour-yogyakarta.jpg",
    estimatedPrice: 1500000,
    priceType: "per_person",
    duration: "Half Day",
    minPax: 1,
    maxPax: 10,
    startTime: "04:00",
    endTime: "10:00",
    includes: ["Jeep transportation", "Guide"],
    excludes: ["Meals", "Personal expenses"],
    vehicleOptions: [
      { id: "jeep-1", name: "Jeep", capacity: 5, pricePerDay: 1500000 },
    ],
    destinationTags: ["Merapi Lava Tour"],
    recommendation: "New",
    status: "active",
  },
  {
    id: "6",
    title: "Sunset Beach Tour",
    description:
      "Relax and enjoy beautiful sunset views at the best beaches in Yogyakarta.",
    imageUrl: "/images/tour-yogyakarta.jpg",
    estimatedPrice: 1200000,
    priceType: "per_person",
    duration: "Half Day",
    minPax: 1,
    maxPax: 10,
    startTime: "13:00",
    endTime: "19:00",
    includes: ["Transportation", "Tour guide"],
    excludes: ["Meals", "Personal expenses"],
    vehicleOptions: [
      { id: "bus-2", name: "Mini Bus", capacity: 10, pricePerDay: 1200000 },
    ],
    destinationTags: ["Pantai Indrayanti", "Pantai Timang"],
    recommendation: "New",
    status: "active",
  },
];